{
  imports = [
    ./alpha.nix
    ./automaton.nix
    ./autopairs.nix
    ./cmp.nix
    ./colorful-menu.nix
    ./colorizer.nix
    ./comment.nix
    ./conform.nix
    ./fidget.nix
    ./fugitive.nix
    ./gitsigns.nix
    ./godot.nix
    ./harpoon.nix
    ./indent.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./neotree.nix
    ./oil.nix
    ./opencode.nix
    ./project.nix
    ./scrolleof.nix
    ./snacks.nix
    ./surround.nix
    ./telescope.nix
    ./todo-comments.nix
    ./trailspace.nix
    ./treesitter.nix
    ./undotree.nix
    ./vim-be-good.nix
    ./vim-tmux.nix
    ./whichkey.nix
  ];
}
