{
  imports = [
    ./alpha.nix
    ./automaton.nix
    ./autopairs.nix
    ./cmp.nix
    ./conform.nix
    ./fidget.nix
    ./fugitive.nix
    ./gitsigns.nix
    ./indent.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./neotree.nix
    ./oil.nix
    ./project.nix
    ./scrolleof.nix
    ./surround.nix
    ./telescope.nix
    ./treesitter.nix
    ./whichkey.nix
  ];
}
